[package]
name = "yew-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.72"
log = "0.4.19"
prokio = "0.1.0"
wasm-bindgen-futures = "0.4.37"
yew = "0.20.0"
